# Generated by Django 4.1.7 on 2023-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.AddField(
            model_name="booking",
            name="user_name",
            field=models.CharField(default="matt", max_length=255),
            preserve_default=False,
        ),
    ]
