# Generated by Django 4.1.7 on 2023-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_remove_booking_user_booking_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reference",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="activated",
            field=models.BooleanField(default=False),
        ),
    ]
