# Generated by Django 4.1.7 on 2023-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_reference_alter_booking_activated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="user_name",
            new_name="userName",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="reference",
        ),
    ]
