# Generated by Django 4.1.7 on 2023-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_rename_user_name_booking_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
