# Generated by Django 4.1.7 on 2023-05-12 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_alter_booking_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seatNumber",
        ),
    ]
